// lib/data/quran/surah_pages.dart

class SurahPage {
  final String surahName;
  final int pageNumber;

  SurahPage({
    required this.surahName,
    required this.pageNumber,
  });
}

 List<SurahPage> surahPages = [
  SurahPage(surahName: "الفَاتِحَة", pageNumber: 1),
  SurahPage(surahName: "البَقَرَة", pageNumber: 2),
  SurahPage(surahName: "آلِ عِمْرَان", pageNumber: 50),
  SurahPage(surahName: "النِّسَاء", pageNumber: 77),
  SurahPage(surahName: "المَائِدَة", pageNumber: 106),
  SurahPage(surahName: "الأَنْعَام", pageNumber: 128),
  SurahPage(surahName: "الأَعْرَاف", pageNumber: 151),
  SurahPage(surahName: "الأَنْفَال", pageNumber: 177),
  SurahPage(surahName: "التَّوْبَة", pageNumber: 187),
  SurahPage(surahName: "يُونُس", pageNumber: 208),
  SurahPage(surahName: "هُود", pageNumber: 221),
  SurahPage(surahName: "يُوسُف", pageNumber: 235),
  SurahPage(surahName: "الرَّعْد", pageNumber: 249),
  SurahPage(surahName: "إِبْرَاهِيم", pageNumber: 255),
  SurahPage(surahName: "الحِجْر", pageNumber: 262),
  SurahPage(surahName: "النَّحْل", pageNumber: 267),
  SurahPage(surahName: "الإِسْرَاء", pageNumber: 282),
  SurahPage(surahName: "الكَهْف", pageNumber: 293),
  SurahPage(surahName: "مَرْيَم", pageNumber: 305),
  SurahPage(surahName: "طه", pageNumber: 312),
   SurahPage(surahName: "الأَنْبِيَاء", pageNumber: 322),
   SurahPage(surahName: "الحَجّ", pageNumber: 332),
   SurahPage(surahName: "المُؤْمِنُون", pageNumber: 342),
   SurahPage(surahName: "النُّور", pageNumber: 350),
   SurahPage(surahName: "الفُرْقَان", pageNumber: 359),
   SurahPage(surahName: "الشُّعَرَاء", pageNumber: 367),
   SurahPage(surahName: "النَّمْل", pageNumber: 377),
   SurahPage(surahName: "القَصَص", pageNumber: 385),
   SurahPage(surahName: "العَنْكَبُوت", pageNumber: 396),
   SurahPage(surahName: "الرُّوم", pageNumber: 404),
   SurahPage(surahName: "لُقْمَان", pageNumber: 411),
   SurahPage(surahName: "السَّجْدَة", pageNumber: 415),
   SurahPage(surahName: "الأَحْزَاب", pageNumber: 418),
   SurahPage(surahName: "سَبَأ", pageNumber: 428),
   SurahPage(surahName: "فَاطِر", pageNumber: 434),
   SurahPage(surahName: "يس", pageNumber: 440),
   SurahPage(surahName: "الصَّافَّات", pageNumber: 446),
   SurahPage(surahName: "ص", pageNumber: 453),
   SurahPage(surahName: "الزُّمَر", pageNumber: 458),
   SurahPage(surahName: "غَافِر", pageNumber: 467),
   SurahPage(surahName: "فُصِّلَتْ", pageNumber: 477),
   SurahPage(surahName: "الشُّورَى", pageNumber: 483),
   SurahPage(surahName: "الزُّخْرُف", pageNumber: 489),
   SurahPage(surahName: "الدُّخَان", pageNumber: 496),
   SurahPage(surahName: "الجَاثِيَة", pageNumber: 499),
   SurahPage(surahName: "الأَحْقَاف", pageNumber: 502),
   SurahPage(surahName: "مُحَمَّد", pageNumber: 507),
   SurahPage(surahName: "الفَتْح", pageNumber: 511),
   SurahPage(surahName: "الحُجُرَات", pageNumber: 515),
   SurahPage(surahName: "ق", pageNumber: 518),
   SurahPage(surahName: "الذَّارِيَات", pageNumber: 520),
   SurahPage(surahName: "الطُّور", pageNumber: 523),
   SurahPage(surahName: "النَّجْم", pageNumber: 526),
   SurahPage(surahName: "القَمَر", pageNumber: 528),
   SurahPage(surahName: "الرَّحْمَن", pageNumber: 531),
   SurahPage(surahName: "الوَاقِعَة", pageNumber: 534),
   SurahPage(surahName: "الحَدِيد", pageNumber: 537),
   SurahPage(surahName: "المُجَادِلَة", pageNumber: 542),
   SurahPage(surahName: "الحَشْر", pageNumber: 545),
   SurahPage(surahName: "المُمْتَحَنَة", pageNumber: 549),
   SurahPage(surahName: "الصَّفّ", pageNumber: 551),
   SurahPage(surahName: "الجُمُعَة", pageNumber: 553),
   SurahPage(surahName: "المُنَافِقُون", pageNumber: 554),
   SurahPage(surahName: "التَّغَابُن", pageNumber: 556),
   SurahPage(surahName: "الطَّلَاق", pageNumber: 558),
   SurahPage(surahName: "التَّحْرِيم", pageNumber: 560),
   SurahPage(surahName: "المُلْك", pageNumber: 562),
   SurahPage(surahName: "القَلَم", pageNumber: 564),
   SurahPage(surahName: "الحَاقَّة", pageNumber: 566),
   SurahPage(surahName: "المَعَارِج", pageNumber: 568),
   SurahPage(surahName: "نُوح", pageNumber: 570),
   SurahPage(surahName: "الجِنّ", pageNumber: 572),
   SurahPage(surahName: "المُزَّمِّل", pageNumber: 574),
   SurahPage(surahName: "المُدَّثِّر", pageNumber: 575),
   SurahPage(surahName: "القِيَامَة", pageNumber: 577),
   SurahPage(surahName: "الإِنْسَان", pageNumber: 578),
   SurahPage(surahName: "المُرْسَلَات", pageNumber: 580),
   SurahPage(surahName: "النَّبَأ", pageNumber: 582),
   SurahPage(surahName: "النَّازِعَات", pageNumber: 583),
   SurahPage(surahName: "عَبَس", pageNumber: 585),
   SurahPage(surahName: "التَّكْوِير", pageNumber: 586),
   SurahPage(surahName: "الانْفِطَار", pageNumber: 587),
   SurahPage(surahName: "المُطَفِّفِين", pageNumber: 587),
   SurahPage(surahName: "الانْشِقَاق", pageNumber: 589),
   SurahPage(surahName: "البُرُوج", pageNumber: 590),
   SurahPage(surahName: "الطَّارِق", pageNumber: 591),
   SurahPage(surahName: "الأَعْلَى", pageNumber: 591),
   SurahPage(surahName: "الغَاشِيَة", pageNumber: 592),
   SurahPage(surahName: "الفَجْر", pageNumber: 593),
   SurahPage(surahName: "البَلَد", pageNumber: 594),
   SurahPage(surahName: "الشَّمْس", pageNumber: 595),
   SurahPage(surahName: "اللَّيْل", pageNumber: 595),
   SurahPage(surahName: "الضُّحَى", pageNumber: 596),
   SurahPage(surahName: "الشَّرْح", pageNumber: 596),
   SurahPage(surahName: "التِّين", pageNumber: 597),
   SurahPage(surahName: "العَلَق", pageNumber: 597),
   SurahPage(surahName: "القَدْر", pageNumber: 598),
   SurahPage(surahName: "البَيِّنَة", pageNumber: 598),
   SurahPage(surahName: "الزَّلْزَلَة", pageNumber: 599),
   SurahPage(surahName: "العَادِيَات", pageNumber: 599),
   SurahPage(surahName: "القَارِعَة", pageNumber: 600),
   SurahPage(surahName: "التَّكَاثُر", pageNumber: 600),
   SurahPage(surahName: "العَصْر", pageNumber: 601),
   SurahPage(surahName: "الهُمَزَة", pageNumber: 601),
   SurahPage(surahName: "الفِيل", pageNumber: 601),
   SurahPage(surahName: "قُرَيْش", pageNumber: 602),
   SurahPage(surahName: "المَاعُون", pageNumber: 602),
   SurahPage(surahName: "الكَوْثَر", pageNumber: 602),
   SurahPage(surahName: "الكَافِرُون", pageNumber: 603),
   SurahPage(surahName: "النَّصْر", pageNumber: 603),
   SurahPage(surahName: "المَسَد", pageNumber: 603),
   SurahPage(surahName: "الإِخْلَاص", pageNumber: 604),
   SurahPage(surahName: "الفَلَق", pageNumber: 604),
   SurahPage(surahName: "النَّاس", pageNumber: 604)
];